"""Tests for the confidence layer and the score channel underneath it.

Two things matter here and they are easy to get wrong in the same direction:

- An *unavailable* signal must never read as a *bad* one. RRF scores are
  ordinal, a foreign retriever may produce nothing at all, and a skipped
  verification produces no accuracy — all of which are None, not zero. A
  zero would be a confident claim that the retrieval was terrible.
- A correct refusal must score low. It is a good response with nothing in it
  to be confident about, and it is exactly the case the structured "I don't
  know" exists to handle.
"""

from langchain_core.documents import Document

from src.generation.citations import parse_citations
from src.generation.confidence import (
    HIGH_THRESHOLD,
    answer_completeness,
    is_full_refusal,
    is_refusal,
    retrieval_confidence,
    score_confidence,
)
from src.generation.verification import unverified_report
from src.retrieval.scores import ScoredDocument, ScoreType


def scored(*pairs: tuple[float, ScoreType]) -> list[ScoredDocument]:
    return [
        ScoredDocument(document=Document(page_content="x"), score=s, score_type=t) for s, t in pairs
    ]


class TestNormalization:
    def test_cross_encoder_logits_squash_to_a_probability(self):
        high = ScoredDocument(Document(page_content="x"), 8.0, ScoreType.CROSS_ENCODER)
        low = ScoredDocument(Document(page_content="x"), -8.0, ScoreType.CROSS_ENCODER)

        assert high.relevance > 0.99
        assert low.relevance < 0.01

    def test_large_negative_logit_does_not_overflow(self):
        """exp(-x) on a -750 logit raises OverflowError on the naive form."""
        item = ScoredDocument(Document(page_content="x"), -750.0, ScoreType.CROSS_ENCODER)

        assert item.relevance == 0.0

    def test_cosine_relevance_passes_through_clamped(self):
        mid = ScoredDocument(Document(page_content="x"), 0.42, ScoreType.COSINE_RELEVANCE)
        negative = ScoredDocument(Document(page_content="x"), -0.2, ScoreType.COSINE_RELEVANCE)

        assert mid.relevance == 0.42
        assert negative.relevance == 0.0

    def test_rrf_carries_no_relevance(self):
        """RRF fuses ranks and throws the scores away, so its output says
        'this came first' and nothing about how relevant first was."""
        item = ScoredDocument(Document(page_content="x"), 0.03, ScoreType.RRF)

        assert item.relevance is None

    def test_unscored_document_carries_no_relevance(self):
        assert ScoredDocument(Document(page_content="x")).relevance is None


class TestRetrievalConfidence:
    def test_weighted_toward_the_best_document(self):
        """One chunk that squarely answers, four fillers, is the normal shape
        of a top-5 over 10-K prose — the mean alone would mark it down."""
        strong_one = retrieval_confidence(
            scored(
                (8.0, ScoreType.CROSS_ENCODER),
                *[(-8.0, ScoreType.CROSS_ENCODER)] * 4,
            )
        )

        assert strong_one > 0.6

    def test_all_irrelevant_scores_near_zero(self):
        assert retrieval_confidence(scored(*[(-8.0, ScoreType.CROSS_ENCODER)] * 5)) < 0.05

    def test_unusable_scores_give_none_not_zero(self):
        assert retrieval_confidence(scored((0.03, ScoreType.RRF))) is None
        assert retrieval_confidence([]) is None

    def test_mixed_availability_uses_what_exists(self):
        result = retrieval_confidence(
            [
                ScoredDocument(Document(page_content="x"), 8.0, ScoreType.CROSS_ENCODER),
                ScoredDocument(Document(page_content="y")),
            ]
        )

        assert result is not None and result > 0.99


# Both generated by the system and recorded in
# evaluation/results/eval_20260808_212927.json, where each was scored as a full
# refusal. The first carries one 'partial' citation verdict, the second two
# 'supported' ones — neither is an answer that said nothing.
JPM_PARTIAL = (
    "I don't have enough information in the available documents to answer this question. "
    "The documents provide details on JPMorgan's CET1 capital ratio, which is 15.7% as of "
    "the latest report [3]. However, the total assets of JPMorgan are not specified in the "
    "provided context."
)

TSLA_PARTIAL = (
    "I don't have enough information in the available documents to answer the question about "
    "Tesla's total operating expenses for 2025. However, Tesla's net income attributable to "
    "common stockholders for 2025 was $3.79 billion [1][3]."
)


class TestRefusalDetection:
    def test_the_wording_the_prompt_asks_for_is_recognized(self):
        answer = (
            "I don't have enough information in the available documents to answer this question."
        )

        assert is_refusal(answer)

    def test_a_real_answer_is_not_a_refusal(self):
        assert not is_refusal("Total net sales were $391.0 billion in fiscal 2024 [1].")

    def test_refusal_with_a_cited_figure_is_not_a_full_refusal(self):
        """The live defect: the marker test fires, but the answer answered."""
        for answer in (JPM_PARTIAL, TSLA_PARTIAL):
            parsed = parse_citations(answer, 5)

            assert is_refusal(answer)
            assert not is_full_refusal(answer, parsed)

    def test_refusal_asserting_nothing_stays_a_full_refusal(self):
        answer = (
            "I don't have enough information in the available documents to answer this question."
        )

        assert is_full_refusal(answer, parse_citations(answer, 5))

    def test_refusal_followed_by_uncited_prose_stays_a_full_refusal(self):
        """Cited claims, not claims. Prose the answer would not attribute is
        not something the system should be credited with having answered."""
        answer = (
            "I don't have enough information in the available documents to answer this question. "
            "JPMorgan is generally regarded as well capitalized relative to its peers."
        )
        parsed = parse_citations(answer, 5)

        assert parsed.claims and not parsed.cited_claims
        assert is_full_refusal(answer, parsed)

    def test_a_real_answer_is_not_a_full_refusal(self):
        answer = "Total net sales were $391.0 billion in fiscal 2024 [1]."

        assert not is_full_refusal(answer, parse_citations(answer, 5))


class TestCompleteness:
    def test_refusal_scores_zero(self):
        answer = "I do not have enough information to answer that."

        assert answer_completeness(answer, parse_citations(answer, 5)) == 0.0

    def test_partial_answer_scores_half(self):
        answer = (
            "Apple's net sales were $391.0 billion [1]. "
            "However, the context does not specify the segment breakdown."
        )

        assert answer_completeness(answer, parse_citations(answer, 5)) == 0.5

    def test_full_answer_scores_one(self):
        answer = "Apple's net sales were $391.0 billion in fiscal 2024 [1]."

        assert answer_completeness(answer, parse_citations(answer, 5)) == 1.0

    def test_text_with_no_claims_scores_zero(self):
        assert answer_completeness("", parse_citations("", 5)) == 0.0

    def test_refusal_with_a_cited_figure_scores_half(self):
        """The three-state scale already had the state these belong in; they
        were being routed to 0.0 because the marker test ran first."""
        for answer in (JPM_PARTIAL, TSLA_PARTIAL):
            assert answer_completeness(answer, parse_citations(answer, 5)) == 0.5

    def test_refusal_with_no_cited_claim_still_scores_zero(self):
        answer = (
            "I don't have enough information in the available documents to answer this question. "
            "JPMorgan is generally regarded as well capitalized relative to its peers."
        )

        assert answer_completeness(answer, parse_citations(answer, 5)) == 0.0


class TestComposite:
    def _confidence(self, answer: str, retrieval: float | None):
        parsed = parse_citations(answer, 5)
        return score_confidence(answer, parsed, unverified_report(parsed), retrieval)

    def test_grounded_answer_over_relevant_chunks_scores_high(self):
        answer = "Net sales were $391.0 billion [1]. Services revenue grew 13% [2]."

        result = self._confidence(answer, 0.95)

        assert result.label == "high"
        assert result.overall > 0.9

    def test_a_correct_refusal_scores_low(self):
        """The response is right and the confidence is low — that pairing is
        the point, and nothing but completeness would notice it."""
        answer = (
            "I don't have enough information in the available documents to answer this question."
        )

        result = self._confidence(answer, 0.8)

        assert result.label == "low"
        assert result.completeness == 0.0

    def test_uncited_answer_over_good_retrieval_is_penalized(self):
        """Grounded-looking prose that attributes nothing is exactly what the
        coverage term exists to catch."""
        cited = self._confidence("Net sales were $391.0 billion [1].", 0.9)
        uncited = self._confidence("Net sales were $391.0 billion.", 0.9)

        assert uncited.overall < cited.overall

    def test_an_uncited_answer_can_never_be_labelled_confident(self):
        """Found in production, not reasoned about: a truncated generation
        stopped before emitting citations, and with retrieval at 0.95 the
        composite still reached 0.675 and read *high* — retrieval's weight
        alone carrying a label for an answer standing on nothing."""
        truncated = self._confidence(
            "Goldman Sachs' total net revenues and return on average common equity are: "
            "For the most recent period",
            0.95,
        )

        assert truncated.coverage == 0.0
        assert truncated.overall > HIGH_THRESHOLD  # the composite still says high
        assert truncated.label == "low"  # the label must not

    def test_the_cap_does_not_touch_properly_cited_answers(self):
        cited = self._confidence("Net sales were $391.0 billion [1].", 0.95)

        assert cited.coverage == 1.0
        assert cited.label == "high"

    def test_missing_retrieval_signal_redistributes_its_weight(self):
        """Unmeasurable must not masquerade as bad: an answer that is fully
        cited and complete scores 1.0 when retrieval is unknown, not 0.5."""
        answer = "Net sales were $391.0 billion [1]."

        assert self._confidence(answer, None).overall == 1.0

    def test_bad_retrieval_drags_a_confident_looking_answer_down(self):
        """The reranker regression is invisible in the answer text — this is
        the signal that surfaces it at query time."""
        answer = "Net sales were $391.0 billion [1]."

        result = self._confidence(answer, 0.05)

        assert result.label != "high"

    def test_a_partial_refusal_is_not_labelled_like_a_refusal(self):
        """`_label` forces "low" whenever completeness is 0.0. A cited, verified
        figure was being presented as no answer at all."""
        result = self._confidence(TSLA_PARTIAL, 0.9)

        assert result.completeness == 0.5
        assert result.label != "low"

    def test_a_partial_refusal_scores_below_the_same_answer_without_the_gap(self):
        """It is still worth less than an answer that covered the question —
        the middle state has to sit between the two, not collapse onto either."""
        full = self._confidence(
            "Tesla's net income attributable to common stockholders for 2025 was "
            "$3.79 billion [1][3].",
            0.9,
        )
        partial = self._confidence(TSLA_PARTIAL, 0.9)
        refused = self._confidence(
            "I don't have enough information in the available documents to answer this question.",
            0.9,
        )

        assert refused.overall < partial.overall < full.overall

    def test_score_stays_inside_the_unit_interval(self):
        answer = "Net sales were $391.0 billion [1]."

        assert 0.0 <= self._confidence(answer, 1.0).overall <= 1.0
        assert 0.0 <= self._confidence("", 0.0).overall <= 1.0
