"""Tests for query-time table continuation.

The bug this exists for: a table crossing a chunk boundary returns a passage
whose numbers look like an answer and are not — Goldman's chunk holding
"Total | Net revenues | $58,283" also holds the *previous* segment's 2.1%
return on equity, while the firmwide 15.0% starts the next chunk. The
properties pinned here are the ones that keep the cure from being worse than
the disease: prose is left alone, citation indices do not move, and a
neighbour is never borrowed across a document or section boundary.
"""

from langchain_core.documents import Document

from src.config import settings
from src.retrieval.expansion import CONTINUATION_MARKER, expand_table_chunks
from src.retrieval.scores import ScoredDocument, ScoreType

TABLE = (
    "Return on average common equity | 2.1 | % | (17.4) | %\n"
    "Total\n"
    "Net revenues | $ | 58,283 | $ | 53,512\n"
    "Compensation and benefits | 18,906 | 16,706"
)
CONTINUATION = (
    "Total operating expenses | 37,544 | 33,767\n"
    "Net earnings to common | $ | 16,300 | $ | 13,525\n"
    "Return on average common equity | 15.0 | % | 12.7 | %"
)
PROSE = (
    "Net revenues in our segments include allocations of interest income and "
    "interest expense based on the funding generated by the respective segments."
)


def doc(text: str, index: int, source: str = "GS_10-K.html", section: str = "MD&A") -> Document:
    return Document(
        page_content=text,
        metadata={
            "ticker": "GS",
            "source_file": source,
            "section_name": section,
            "chunk_index": index,
        },
    )


def scored(*documents: Document) -> list[ScoredDocument]:
    return [
        ScoredDocument(document=d, score=5.0 - i, score_type=ScoreType.CROSS_ENCODER)
        for i, d in enumerate(documents)
    ]


class FakeStore:
    """Returns the chunk whose metadata matches an equality where-clause."""

    def __init__(self, *documents: Document):
        self.corpus = documents
        self.queries: list[dict] = []

    def get_all_documents(self, filter_dict: dict | None = None) -> list[Document]:
        self.queries.append(filter_dict or {})
        wanted = {
            list(clause.values())[0]["$eq"]: list(clause.keys())[0]
            for clause in (filter_dict or {}).get("$and", [])
        }
        expected = {field: value for value, field in wanted.items()}
        return [
            d
            for d in self.corpus
            if all(d.metadata.get(field) == value for field, value in expected.items())
        ]


class TestExpansion:
    def test_a_table_gains_the_following_chunk(self):
        store = FakeStore(doc(CONTINUATION, 984))
        items = scored(doc(TABLE, 983))

        expand_table_chunks(items, store)

        text = items[0].document.page_content
        assert CONTINUATION_MARKER in text
        assert "15.0" in text, "the firmwide row is the whole point"
        assert text.startswith(TABLE), "the retrieved chunk still leads"

    def test_prose_is_left_alone(self):
        store = FakeStore(doc(CONTINUATION, 986))
        items = scored(doc(PROSE, 985))

        expand_table_chunks(items, store)

        assert items[0].document.page_content == PROSE
        assert not store.queries, "prose should not even be looked up"

    def test_the_returned_list_keeps_its_shape(self):
        """Citation indices are positional: adding, dropping or reordering
        documents here would renumber the citations the model is about to
        emit against the list it was shown."""
        store = FakeStore(doc(CONTINUATION, 984))
        items = scored(doc(TABLE, 983), doc(PROSE, 500))
        before = [item.score for item in items]

        result = expand_table_chunks(items, store)

        assert len(result) == 2
        assert [item.score for item in result] == before
        assert result[1].document.page_content == PROSE

    def test_a_neighbour_already_retrieved_is_not_duplicated(self):
        """Otherwise one passage occupies two of the five citation slots."""
        store = FakeStore(doc(CONTINUATION, 984))
        items = scored(doc(TABLE, 983), doc(CONTINUATION, 984))

        expand_table_chunks(items, store)

        assert CONTINUATION_MARKER not in items[0].document.page_content

    def test_never_crosses_a_document_boundary(self):
        store = FakeStore(doc(CONTINUATION, 984, source="JPM_10-K.html"))
        items = scored(doc(TABLE, 983, source="GS_10-K.html"))

        expand_table_chunks(items, store)

        assert CONTINUATION_MARKER not in items[0].document.page_content

    def test_never_crosses_a_section_boundary(self):
        store = FakeStore(doc(CONTINUATION, 984, section="Item 8"))
        items = scored(doc(TABLE, 983, section="MD&A"))

        expand_table_chunks(items, store)

        assert CONTINUATION_MARKER not in items[0].document.page_content

    def test_the_last_chunk_in_a_section_expands_to_nothing(self):
        store = FakeStore()
        items = scored(doc(TABLE, 983))

        expand_table_chunks(items, store)

        assert items[0].document.page_content == TABLE

    def test_the_setting_switches_it_off(self, monkeypatch):
        monkeypatch.setattr(settings, "table_expansion_enabled", False)
        store = FakeStore(doc(CONTINUATION, 984))
        items = scored(doc(TABLE, 983))

        expand_table_chunks(items, store)

        assert items[0].document.page_content == TABLE
        assert not store.queries
